apiVersion: batch/v1
kind: Job
metadata:
  name: batch-check-job
spec:
  template:
    metadata:
      name: batch-check-job
    spec:
      containers:
      - name: batch-check
        image: loremitacr.azurecr.io/goat/k8s-goat-batch-check
        # command:
        #  - "bin/sh"
        #  - "-c"
        #  - "htop"
      restartPolicy: Never
      